language: python

python:
  - 2.7
  - 3.7
  - 3.8

matrix:
  include:
    - name: "linting"
      python: 3.7
      before_install:
      install: pip install tox
      script: tox -e linting
      after_success:

install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - pip install -U -e ".[test]"

script:
  - coverage run -m zope.testrunner --test-path=src

after_success:
  - coveralls

cache: pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
